### ISSUE TITLE
Adding more colombia municipal data

### ISSUE THREAD

**Issue by chendaniely** [BuzzFeedNews/zika-data#9]
Just noticed there was a parser for the Colombia PDFs.

I can't seem to figure out how to use them.
There are 3 more new reports I'd like to add, but I can't seem to get the pdf into `stdin` for the script to parse.

Should I be loading `parse-colombia-municipal.py` as a python module? or is there a specific way to run it via command line by passing it a pdf to parse?

**Comment by jsvine** [comment]
Hi Daniel, and good eye! Typically, you'd run it this way:

``` sh
python scripts/parse-colombia-municipal.py < path/to/pdf/file.pdf > output.csv
```

(You'll also need to `pip install` `pdfplumber` and `pandas`.) 

Does that work for you?

If not, I can give it a shot in the next couple of days. The format of the Colombia PDFs kept shifting slightly from week to week, and I stopped updating the parser, so no guarantee it'll work, unfortunately.

**Comment by chendaniely** [comment]
``` bash
$ python scripts/parse-colombia-municipal.py < ../zika/Colombia/Municipality_Zika/original_reports/CONTEO\ CASOS\ ZIKA\ MUNICIPIOS\ SE\ 08\ 2016.pdf > output_08.csv
```

``` python
Traceback (most recent call last):
  File "scripts/parse-colombia-municipal.py", line 66, in <module>
    data = parse(pdf)
  File "scripts/parse-colombia-municipal.py", line 42, in parse
    data = pdfplumber.utils.extract_columns(data_chars, x_tolerance=1, y_tolerance=1)
AttributeError: 'module' object has no attribute 'extract_columns'
```

Oh well... worth a try.  I'll tinker with the script later.

Need do it the 'stupid' way to just get something out there.

**Comment by jsvine** [comment]
Ah, yes, that script is out of date/sync with the latest version of `pdfplumber`. I just pushed a new version of the script that _should_ work. One difference: To make it slightly easier to test, you pass the PDF as an argument rather than as `stdin`. So it'd be:

``` sh
python scripts/parse-colombia-municipal.py ../zika/Colombia/Municipality_Zika/original_reports/CONTEO\ CASOS\ ZIKA\ MUNICIPIOS\ SE\ 08\ 2016.pdf > output_08.csv
```

Does that work for you?
